// This file is generated by rust-protobuf 2.7.0. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `chunk_dictionary.proto`

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_7_0;

#[derive(PartialEq,Clone,Default)]
pub struct ChunkDescriptor {
    // message fields
    pub checksum: ::std::vec::Vec<u8>,
    pub archive_size: u32,
    pub archive_offset: u64,
    pub source_size: u32,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a ChunkDescriptor {
    fn default() -> &'a ChunkDescriptor {
        <ChunkDescriptor as ::protobuf::Message>::default_instance()
    }
}

impl ChunkDescriptor {
    pub fn new() -> ChunkDescriptor {
        ::std::default::Default::default()
    }

    // bytes checksum = 1;


    pub fn get_checksum(&self) -> &[u8] {
        &self.checksum
    }
    pub fn clear_checksum(&mut self) {
        self.checksum.clear();
    }

    // Param is passed by value, moved
    pub fn set_checksum(&mut self, v: ::std::vec::Vec<u8>) {
        self.checksum = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_checksum(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.checksum
    }

    // Take field
    pub fn take_checksum(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.checksum, ::std::vec::Vec::new())
    }

    // uint32 archive_size = 3;


    pub fn get_archive_size(&self) -> u32 {
        self.archive_size
    }
    pub fn clear_archive_size(&mut self) {
        self.archive_size = 0;
    }

    // Param is passed by value, moved
    pub fn set_archive_size(&mut self, v: u32) {
        self.archive_size = v;
    }

    // uint64 archive_offset = 4;


    pub fn get_archive_offset(&self) -> u64 {
        self.archive_offset
    }
    pub fn clear_archive_offset(&mut self) {
        self.archive_offset = 0;
    }

    // Param is passed by value, moved
    pub fn set_archive_offset(&mut self, v: u64) {
        self.archive_offset = v;
    }

    // uint32 source_size = 5;


    pub fn get_source_size(&self) -> u32 {
        self.source_size
    }
    pub fn clear_source_size(&mut self) {
        self.source_size = 0;
    }

    // Param is passed by value, moved
    pub fn set_source_size(&mut self, v: u32) {
        self.source_size = v;
    }
}

impl ::protobuf::Message for ChunkDescriptor {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.checksum)?;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.archive_size = tmp;
                },
                4 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.archive_offset = tmp;
                },
                5 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.source_size = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.checksum.is_empty() {
            my_size += ::protobuf::rt::bytes_size(1, &self.checksum);
        }
        if self.archive_size != 0 {
            my_size += ::protobuf::rt::value_size(3, self.archive_size, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.archive_offset != 0 {
            my_size += ::protobuf::rt::value_size(4, self.archive_offset, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.source_size != 0 {
            my_size += ::protobuf::rt::value_size(5, self.source_size, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if !self.checksum.is_empty() {
            os.write_bytes(1, &self.checksum)?;
        }
        if self.archive_size != 0 {
            os.write_uint32(3, self.archive_size)?;
        }
        if self.archive_offset != 0 {
            os.write_uint64(4, self.archive_offset)?;
        }
        if self.source_size != 0 {
            os.write_uint32(5, self.source_size)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ChunkDescriptor {
        ChunkDescriptor::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "checksum",
                    |m: &ChunkDescriptor| { &m.checksum },
                    |m: &mut ChunkDescriptor| { &mut m.checksum },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                    "archive_size",
                    |m: &ChunkDescriptor| { &m.archive_size },
                    |m: &mut ChunkDescriptor| { &mut m.archive_size },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "archive_offset",
                    |m: &ChunkDescriptor| { &m.archive_offset },
                    |m: &mut ChunkDescriptor| { &mut m.archive_offset },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                    "source_size",
                    |m: &ChunkDescriptor| { &m.source_size },
                    |m: &mut ChunkDescriptor| { &mut m.source_size },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<ChunkDescriptor>(
                    "ChunkDescriptor",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static ChunkDescriptor {
        static mut instance: ::protobuf::lazy::Lazy<ChunkDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ChunkDescriptor,
        };
        unsafe {
            instance.get(ChunkDescriptor::new)
        }
    }
}

impl ::protobuf::Clear for ChunkDescriptor {
    fn clear(&mut self) {
        self.checksum.clear();
        self.archive_size = 0;
        self.archive_offset = 0;
        self.source_size = 0;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ChunkDescriptor {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ChunkDescriptor {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct ChunkerParameters {
    // message fields
    pub chunk_filter_bits: u32,
    pub min_chunk_size: u32,
    pub max_chunk_size: u32,
    pub hash_window_size: u32,
    pub chunk_hash_length: u32,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a ChunkerParameters {
    fn default() -> &'a ChunkerParameters {
        <ChunkerParameters as ::protobuf::Message>::default_instance()
    }
}

impl ChunkerParameters {
    pub fn new() -> ChunkerParameters {
        ::std::default::Default::default()
    }

    // uint32 chunk_filter_bits = 1;


    pub fn get_chunk_filter_bits(&self) -> u32 {
        self.chunk_filter_bits
    }
    pub fn clear_chunk_filter_bits(&mut self) {
        self.chunk_filter_bits = 0;
    }

    // Param is passed by value, moved
    pub fn set_chunk_filter_bits(&mut self, v: u32) {
        self.chunk_filter_bits = v;
    }

    // uint32 min_chunk_size = 2;


    pub fn get_min_chunk_size(&self) -> u32 {
        self.min_chunk_size
    }
    pub fn clear_min_chunk_size(&mut self) {
        self.min_chunk_size = 0;
    }

    // Param is passed by value, moved
    pub fn set_min_chunk_size(&mut self, v: u32) {
        self.min_chunk_size = v;
    }

    // uint32 max_chunk_size = 3;


    pub fn get_max_chunk_size(&self) -> u32 {
        self.max_chunk_size
    }
    pub fn clear_max_chunk_size(&mut self) {
        self.max_chunk_size = 0;
    }

    // Param is passed by value, moved
    pub fn set_max_chunk_size(&mut self, v: u32) {
        self.max_chunk_size = v;
    }

    // uint32 hash_window_size = 4;


    pub fn get_hash_window_size(&self) -> u32 {
        self.hash_window_size
    }
    pub fn clear_hash_window_size(&mut self) {
        self.hash_window_size = 0;
    }

    // Param is passed by value, moved
    pub fn set_hash_window_size(&mut self, v: u32) {
        self.hash_window_size = v;
    }

    // uint32 chunk_hash_length = 5;


    pub fn get_chunk_hash_length(&self) -> u32 {
        self.chunk_hash_length
    }
    pub fn clear_chunk_hash_length(&mut self) {
        self.chunk_hash_length = 0;
    }

    // Param is passed by value, moved
    pub fn set_chunk_hash_length(&mut self, v: u32) {
        self.chunk_hash_length = v;
    }
}

impl ::protobuf::Message for ChunkerParameters {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.chunk_filter_bits = tmp;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.min_chunk_size = tmp;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.max_chunk_size = tmp;
                },
                4 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.hash_window_size = tmp;
                },
                5 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.chunk_hash_length = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.chunk_filter_bits != 0 {
            my_size += ::protobuf::rt::value_size(1, self.chunk_filter_bits, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.min_chunk_size != 0 {
            my_size += ::protobuf::rt::value_size(2, self.min_chunk_size, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.max_chunk_size != 0 {
            my_size += ::protobuf::rt::value_size(3, self.max_chunk_size, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.hash_window_size != 0 {
            my_size += ::protobuf::rt::value_size(4, self.hash_window_size, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.chunk_hash_length != 0 {
            my_size += ::protobuf::rt::value_size(5, self.chunk_hash_length, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if self.chunk_filter_bits != 0 {
            os.write_uint32(1, self.chunk_filter_bits)?;
        }
        if self.min_chunk_size != 0 {
            os.write_uint32(2, self.min_chunk_size)?;
        }
        if self.max_chunk_size != 0 {
            os.write_uint32(3, self.max_chunk_size)?;
        }
        if self.hash_window_size != 0 {
            os.write_uint32(4, self.hash_window_size)?;
        }
        if self.chunk_hash_length != 0 {
            os.write_uint32(5, self.chunk_hash_length)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ChunkerParameters {
        ChunkerParameters::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                    "chunk_filter_bits",
                    |m: &ChunkerParameters| { &m.chunk_filter_bits },
                    |m: &mut ChunkerParameters| { &mut m.chunk_filter_bits },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                    "min_chunk_size",
                    |m: &ChunkerParameters| { &m.min_chunk_size },
                    |m: &mut ChunkerParameters| { &mut m.min_chunk_size },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                    "max_chunk_size",
                    |m: &ChunkerParameters| { &m.max_chunk_size },
                    |m: &mut ChunkerParameters| { &mut m.max_chunk_size },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                    "hash_window_size",
                    |m: &ChunkerParameters| { &m.hash_window_size },
                    |m: &mut ChunkerParameters| { &mut m.hash_window_size },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                    "chunk_hash_length",
                    |m: &ChunkerParameters| { &m.chunk_hash_length },
                    |m: &mut ChunkerParameters| { &mut m.chunk_hash_length },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<ChunkerParameters>(
                    "ChunkerParameters",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static ChunkerParameters {
        static mut instance: ::protobuf::lazy::Lazy<ChunkerParameters> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ChunkerParameters,
        };
        unsafe {
            instance.get(ChunkerParameters::new)
        }
    }
}

impl ::protobuf::Clear for ChunkerParameters {
    fn clear(&mut self) {
        self.chunk_filter_bits = 0;
        self.min_chunk_size = 0;
        self.max_chunk_size = 0;
        self.hash_window_size = 0;
        self.chunk_hash_length = 0;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ChunkerParameters {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ChunkerParameters {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct ChunkCompression {
    // message fields
    pub compression: ChunkCompression_CompressionType,
    pub compression_level: u32,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a ChunkCompression {
    fn default() -> &'a ChunkCompression {
        <ChunkCompression as ::protobuf::Message>::default_instance()
    }
}

impl ChunkCompression {
    pub fn new() -> ChunkCompression {
        ::std::default::Default::default()
    }

    // .chunk_dictionary.ChunkCompression.CompressionType compression = 2;


    pub fn get_compression(&self) -> ChunkCompression_CompressionType {
        self.compression
    }
    pub fn clear_compression(&mut self) {
        self.compression = ChunkCompression_CompressionType::NONE;
    }

    // Param is passed by value, moved
    pub fn set_compression(&mut self, v: ChunkCompression_CompressionType) {
        self.compression = v;
    }

    // uint32 compression_level = 3;


    pub fn get_compression_level(&self) -> u32 {
        self.compression_level
    }
    pub fn clear_compression_level(&mut self) {
        self.compression_level = 0;
    }

    // Param is passed by value, moved
    pub fn set_compression_level(&mut self, v: u32) {
        self.compression_level = v;
    }
}

impl ::protobuf::Message for ChunkCompression {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                2 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.compression, 2, &mut self.unknown_fields)?
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.compression_level = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.compression != ChunkCompression_CompressionType::NONE {
            my_size += ::protobuf::rt::enum_size(2, self.compression);
        }
        if self.compression_level != 0 {
            my_size += ::protobuf::rt::value_size(3, self.compression_level, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if self.compression != ChunkCompression_CompressionType::NONE {
            os.write_enum(2, self.compression.value())?;
        }
        if self.compression_level != 0 {
            os.write_uint32(3, self.compression_level)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ChunkCompression {
        ChunkCompression::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<ChunkCompression_CompressionType>>(
                    "compression",
                    |m: &ChunkCompression| { &m.compression },
                    |m: &mut ChunkCompression| { &mut m.compression },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                    "compression_level",
                    |m: &ChunkCompression| { &m.compression_level },
                    |m: &mut ChunkCompression| { &mut m.compression_level },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<ChunkCompression>(
                    "ChunkCompression",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static ChunkCompression {
        static mut instance: ::protobuf::lazy::Lazy<ChunkCompression> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ChunkCompression,
        };
        unsafe {
            instance.get(ChunkCompression::new)
        }
    }
}

impl ::protobuf::Clear for ChunkCompression {
    fn clear(&mut self) {
        self.compression = ChunkCompression_CompressionType::NONE;
        self.compression_level = 0;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ChunkCompression {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ChunkCompression {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(Clone,PartialEq,Eq,Debug,Hash)]
pub enum ChunkCompression_CompressionType {
    NONE = 0,
    LZMA = 1,
    ZSTD = 2,
}

impl ::protobuf::ProtobufEnum for ChunkCompression_CompressionType {
    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<ChunkCompression_CompressionType> {
        match value {
            0 => ::std::option::Option::Some(ChunkCompression_CompressionType::NONE),
            1 => ::std::option::Option::Some(ChunkCompression_CompressionType::LZMA),
            2 => ::std::option::Option::Some(ChunkCompression_CompressionType::ZSTD),
            _ => ::std::option::Option::None
        }
    }

    fn values() -> &'static [Self] {
        static values: &'static [ChunkCompression_CompressionType] = &[
            ChunkCompression_CompressionType::NONE,
            ChunkCompression_CompressionType::LZMA,
            ChunkCompression_CompressionType::ZSTD,
        ];
        values
    }

    fn enum_descriptor_static() -> &'static ::protobuf::reflect::EnumDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::EnumDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                ::protobuf::reflect::EnumDescriptor::new("ChunkCompression_CompressionType", file_descriptor_proto())
            })
        }
    }
}

impl ::std::marker::Copy for ChunkCompression_CompressionType {
}

impl ::std::default::Default for ChunkCompression_CompressionType {
    fn default() -> Self {
        ChunkCompression_CompressionType::NONE
    }
}

impl ::protobuf::reflect::ProtobufValue for ChunkCompression_CompressionType {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Enum(self.descriptor())
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct ChunkDictionary {
    // message fields
    pub application_version: ::std::string::String,
    pub source_checksum: ::std::vec::Vec<u8>,
    pub source_total_size: u64,
    pub chunker_params: ::protobuf::SingularPtrField<ChunkerParameters>,
    pub chunk_compression: ::protobuf::SingularPtrField<ChunkCompression>,
    pub rebuild_order: ::std::vec::Vec<u32>,
    pub chunk_descriptors: ::protobuf::RepeatedField<ChunkDescriptor>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a ChunkDictionary {
    fn default() -> &'a ChunkDictionary {
        <ChunkDictionary as ::protobuf::Message>::default_instance()
    }
}

impl ChunkDictionary {
    pub fn new() -> ChunkDictionary {
        ::std::default::Default::default()
    }

    // string application_version = 1;


    pub fn get_application_version(&self) -> &str {
        &self.application_version
    }
    pub fn clear_application_version(&mut self) {
        self.application_version.clear();
    }

    // Param is passed by value, moved
    pub fn set_application_version(&mut self, v: ::std::string::String) {
        self.application_version = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_application_version(&mut self) -> &mut ::std::string::String {
        &mut self.application_version
    }

    // Take field
    pub fn take_application_version(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.application_version, ::std::string::String::new())
    }

    // bytes source_checksum = 2;


    pub fn get_source_checksum(&self) -> &[u8] {
        &self.source_checksum
    }
    pub fn clear_source_checksum(&mut self) {
        self.source_checksum.clear();
    }

    // Param is passed by value, moved
    pub fn set_source_checksum(&mut self, v: ::std::vec::Vec<u8>) {
        self.source_checksum = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_source_checksum(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.source_checksum
    }

    // Take field
    pub fn take_source_checksum(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.source_checksum, ::std::vec::Vec::new())
    }

    // uint64 source_total_size = 3;


    pub fn get_source_total_size(&self) -> u64 {
        self.source_total_size
    }
    pub fn clear_source_total_size(&mut self) {
        self.source_total_size = 0;
    }

    // Param is passed by value, moved
    pub fn set_source_total_size(&mut self, v: u64) {
        self.source_total_size = v;
    }

    // .chunk_dictionary.ChunkerParameters chunker_params = 4;


    pub fn get_chunker_params(&self) -> &ChunkerParameters {
        self.chunker_params.as_ref().unwrap_or_else(|| ChunkerParameters::default_instance())
    }
    pub fn clear_chunker_params(&mut self) {
        self.chunker_params.clear();
    }

    pub fn has_chunker_params(&self) -> bool {
        self.chunker_params.is_some()
    }

    // Param is passed by value, moved
    pub fn set_chunker_params(&mut self, v: ChunkerParameters) {
        self.chunker_params = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_chunker_params(&mut self) -> &mut ChunkerParameters {
        if self.chunker_params.is_none() {
            self.chunker_params.set_default();
        }
        self.chunker_params.as_mut().unwrap()
    }

    // Take field
    pub fn take_chunker_params(&mut self) -> ChunkerParameters {
        self.chunker_params.take().unwrap_or_else(|| ChunkerParameters::new())
    }

    // .chunk_dictionary.ChunkCompression chunk_compression = 5;


    pub fn get_chunk_compression(&self) -> &ChunkCompression {
        self.chunk_compression.as_ref().unwrap_or_else(|| ChunkCompression::default_instance())
    }
    pub fn clear_chunk_compression(&mut self) {
        self.chunk_compression.clear();
    }

    pub fn has_chunk_compression(&self) -> bool {
        self.chunk_compression.is_some()
    }

    // Param is passed by value, moved
    pub fn set_chunk_compression(&mut self, v: ChunkCompression) {
        self.chunk_compression = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_chunk_compression(&mut self) -> &mut ChunkCompression {
        if self.chunk_compression.is_none() {
            self.chunk_compression.set_default();
        }
        self.chunk_compression.as_mut().unwrap()
    }

    // Take field
    pub fn take_chunk_compression(&mut self) -> ChunkCompression {
        self.chunk_compression.take().unwrap_or_else(|| ChunkCompression::new())
    }

    // repeated uint32 rebuild_order = 6;


    pub fn get_rebuild_order(&self) -> &[u32] {
        &self.rebuild_order
    }
    pub fn clear_rebuild_order(&mut self) {
        self.rebuild_order.clear();
    }

    // Param is passed by value, moved
    pub fn set_rebuild_order(&mut self, v: ::std::vec::Vec<u32>) {
        self.rebuild_order = v;
    }

    // Mutable pointer to the field.
    pub fn mut_rebuild_order(&mut self) -> &mut ::std::vec::Vec<u32> {
        &mut self.rebuild_order
    }

    // Take field
    pub fn take_rebuild_order(&mut self) -> ::std::vec::Vec<u32> {
        ::std::mem::replace(&mut self.rebuild_order, ::std::vec::Vec::new())
    }

    // repeated .chunk_dictionary.ChunkDescriptor chunk_descriptors = 7;


    pub fn get_chunk_descriptors(&self) -> &[ChunkDescriptor] {
        &self.chunk_descriptors
    }
    pub fn clear_chunk_descriptors(&mut self) {
        self.chunk_descriptors.clear();
    }

    // Param is passed by value, moved
    pub fn set_chunk_descriptors(&mut self, v: ::protobuf::RepeatedField<ChunkDescriptor>) {
        self.chunk_descriptors = v;
    }

    // Mutable pointer to the field.
    pub fn mut_chunk_descriptors(&mut self) -> &mut ::protobuf::RepeatedField<ChunkDescriptor> {
        &mut self.chunk_descriptors
    }

    // Take field
    pub fn take_chunk_descriptors(&mut self) -> ::protobuf::RepeatedField<ChunkDescriptor> {
        ::std::mem::replace(&mut self.chunk_descriptors, ::protobuf::RepeatedField::new())
    }
}

impl ::protobuf::Message for ChunkDictionary {
    fn is_initialized(&self) -> bool {
        for v in &self.chunker_params {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.chunk_compression {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.chunk_descriptors {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.application_version)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.source_checksum)?;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.source_total_size = tmp;
                },
                4 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.chunker_params)?;
                },
                5 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.chunk_compression)?;
                },
                6 => {
                    ::protobuf::rt::read_repeated_uint32_into(wire_type, is, &mut self.rebuild_order)?;
                },
                7 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.chunk_descriptors)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.application_version.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.application_version);
        }
        if !self.source_checksum.is_empty() {
            my_size += ::protobuf::rt::bytes_size(2, &self.source_checksum);
        }
        if self.source_total_size != 0 {
            my_size += ::protobuf::rt::value_size(3, self.source_total_size, ::protobuf::wire_format::WireTypeVarint);
        }
        if let Some(ref v) = self.chunker_params.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if let Some(ref v) = self.chunk_compression.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        for value in &self.rebuild_order {
            my_size += ::protobuf::rt::value_size(6, *value, ::protobuf::wire_format::WireTypeVarint);
        };
        for value in &self.chunk_descriptors {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if !self.application_version.is_empty() {
            os.write_string(1, &self.application_version)?;
        }
        if !self.source_checksum.is_empty() {
            os.write_bytes(2, &self.source_checksum)?;
        }
        if self.source_total_size != 0 {
            os.write_uint64(3, self.source_total_size)?;
        }
        if let Some(ref v) = self.chunker_params.as_ref() {
            os.write_tag(4, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if let Some(ref v) = self.chunk_compression.as_ref() {
            os.write_tag(5, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        for v in &self.rebuild_order {
            os.write_uint32(6, *v)?;
        };
        for v in &self.chunk_descriptors {
            os.write_tag(7, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ChunkDictionary {
        ChunkDictionary::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "application_version",
                    |m: &ChunkDictionary| { &m.application_version },
                    |m: &mut ChunkDictionary| { &mut m.application_version },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                    "source_checksum",
                    |m: &ChunkDictionary| { &m.source_checksum },
                    |m: &mut ChunkDictionary| { &mut m.source_checksum },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                    "source_total_size",
                    |m: &ChunkDictionary| { &m.source_total_size },
                    |m: &mut ChunkDictionary| { &mut m.source_total_size },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<ChunkerParameters>>(
                    "chunker_params",
                    |m: &ChunkDictionary| { &m.chunker_params },
                    |m: &mut ChunkDictionary| { &mut m.chunker_params },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<ChunkCompression>>(
                    "chunk_compression",
                    |m: &ChunkDictionary| { &m.chunk_compression },
                    |m: &mut ChunkDictionary| { &mut m.chunk_compression },
                ));
                fields.push(::protobuf::reflect::accessor::make_vec_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                    "rebuild_order",
                    |m: &ChunkDictionary| { &m.rebuild_order },
                    |m: &mut ChunkDictionary| { &mut m.rebuild_order },
                ));
                fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<ChunkDescriptor>>(
                    "chunk_descriptors",
                    |m: &ChunkDictionary| { &m.chunk_descriptors },
                    |m: &mut ChunkDictionary| { &mut m.chunk_descriptors },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<ChunkDictionary>(
                    "ChunkDictionary",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static ChunkDictionary {
        static mut instance: ::protobuf::lazy::Lazy<ChunkDictionary> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ChunkDictionary,
        };
        unsafe {
            instance.get(ChunkDictionary::new)
        }
    }
}

impl ::protobuf::Clear for ChunkDictionary {
    fn clear(&mut self) {
        self.application_version.clear();
        self.source_checksum.clear();
        self.source_total_size = 0;
        self.chunker_params.clear();
        self.chunk_compression.clear();
        self.rebuild_order.clear();
        self.chunk_descriptors.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ChunkDictionary {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ChunkDictionary {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x16chunk_dictionary.proto\x12\x10chunk_dictionary\"\x98\x01\n\x0fChun\
    kDescriptor\x12\x1a\n\x08checksum\x18\x01\x20\x01(\x0cR\x08checksum\x12!\
    \n\x0carchive_size\x18\x03\x20\x01(\rR\x0barchiveSize\x12%\n\x0earchive_\
    offset\x18\x04\x20\x01(\x04R\rarchiveOffset\x12\x1f\n\x0bsource_size\x18\
    \x05\x20\x01(\rR\nsourceSize\"\xe1\x01\n\x11ChunkerParameters\x12*\n\x11\
    chunk_filter_bits\x18\x01\x20\x01(\rR\x0fchunkFilterBits\x12$\n\x0emin_c\
    hunk_size\x18\x02\x20\x01(\rR\x0cminChunkSize\x12$\n\x0emax_chunk_size\
    \x18\x03\x20\x01(\rR\x0cmaxChunkSize\x12(\n\x10hash_window_size\x18\x04\
    \x20\x01(\rR\x0ehashWindowSize\x12*\n\x11chunk_hash_length\x18\x05\x20\
    \x01(\rR\x0fchunkHashLength\"\xc6\x01\n\x10ChunkCompression\x12T\n\x0bco\
    mpression\x18\x02\x20\x01(\x0e22.chunk_dictionary.ChunkCompression.Compr\
    essionTypeR\x0bcompression\x12+\n\x11compression_level\x18\x03\x20\x01(\
    \rR\x10compressionLevel\"/\n\x0fCompressionType\x12\x08\n\x04NONE\x10\0\
    \x12\x08\n\x04LZMA\x10\x01\x12\x08\n\x04ZSTD\x10\x02\"\xa9\x03\n\x0fChun\
    kDictionary\x12/\n\x13application_version\x18\x01\x20\x01(\tR\x12applica\
    tionVersion\x12'\n\x0fsource_checksum\x18\x02\x20\x01(\x0cR\x0esourceChe\
    cksum\x12*\n\x11source_total_size\x18\x03\x20\x01(\x04R\x0fsourceTotalSi\
    ze\x12J\n\x0echunker_params\x18\x04\x20\x01(\x0b2#.chunk_dictionary.Chun\
    kerParametersR\rchunkerParams\x12O\n\x11chunk_compression\x18\x05\x20\
    \x01(\x0b2\".chunk_dictionary.ChunkCompressionR\x10chunkCompression\x12#\
    \n\rrebuild_order\x18\x06\x20\x03(\rR\x0crebuildOrder\x12N\n\x11chunk_de\
    scriptors\x18\x07\x20\x03(\x0b2!.chunk_dictionary.ChunkDescriptorR\x10ch\
    unkDescriptorsb\x06proto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy {
    lock: ::protobuf::lazy::ONCE_INIT,
    ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
};

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
